### ISSUE TITLE
if...is not...

### ISSUE THREAD

**Issue by phroiland** [gkovacs/remove_miner_fees#10]
Why not just make a statement to check for your address instead of collecting all of their addresses? They could, theoretically, dynamically update their address every round.

**Comment by SimoneHz** [comment]
I did it in my script. I released it on my fork:
https://github.com/SimoneHz/remove_miner_fees
Let me know if you find some issues.

**Comment by ghost** [comment]
@SimoneHz 

Good Work :)
unfortunatly i have trouble to get it working. I am using nfqueue from pip(no debuntu here)
https://pypi.python.org/pypi/NetfilterQueue

this seems to be different to yours. There are no methods like get_data or set_verdict_modified

Which version is yours?

I tried to make my own. But something is still missing. Claymore connection timeouts. 
https://pastebin.com/eiJsAnYn

can you point me please in right direction?

EDIT:
Sorry, read further its in the Readme. Got it working by extracting includes from debs from packages.ubuntu. Thanks.

**Comment by SimoneHz** [comment]
Hi @derdigge 
Perfect! I was just checking my version of python-nfqueue --> 0.5-1build2.
When I find a bit of time I will try to make the script a bit more easy to configure.

**Comment by ghost** [comment]
@SimoneHz 

Thats great maybe one which is inline with current pip versions.
I was verry close with mine. see pastebin.

**Comment by tsauce** [comment]
@SimoneHz your script doesn't have logging output, how can you tell if it works ? Also why do you have an iptables command to FORWARD? This deviates from what was originally in @demonlj and @gkovacs script. Was just curious why it was put in.
